#!/data/data/com.termux/files/usr/bin/sh
termux-wake-lock
sshd
sv-enable crond
su -c dumpsys battery set level 100
su -c svc power stayon true
su -c dumpsys deviceidle whitelist +com.termux.boot
su -c dumpsys deviceidle whitelist +com.termux
su -c settings put global system_capabilities 100
su -c settings put global sem_enhanced_cpu_responsiveness 1
su -c settings put global wifi_sleep_policy 2
~/jobscheduler.sh
